-- INSERT INTO horoscope_db (zodiac_sign, dates, element)
-- VALUES  ("Aries", "March 21-April 19", "Fire"),
--         ("Taurus", "April 20-May 20", "Earth"),
--         ("Gemini", "May 21-June 20", "Air"),
--         ("Cancer", "June21-July 22", "Water"),
--         ("Leo", "July 23-August 22", "Fire"),
--         ("Virgo", "August 23-September 22", "Earth"),
--         ("Libra", "September 23-October 22", "Air"),
--         ("Scorpio", "October 23-November 21", "Water"),
--         ("Sagittaruis", "November 22-December 21", "Fire"),
--         ("Capricornus", "December 22-January 19", "Earth"),
--         ("Aquarius", "January 20-February 18", "Air"),
--         ("Pisces", "February 19-March 20", "Water");